image: python:2.7

stages:
 - build
 - publish

build_job:
  stage: build
  script:
    - "pip install -U platformio"
    - "VERSION=$(sed -n 's/^.*FW_VERSION \\\"\\(.*\\)\\\"/\\1/p' <src/config.hpp)"
    - "echo $VERSION"
    - "pio run -e esp32dev"
  artifacts: 
    paths:
      - .pio/build/esp32dev/firmware.bin
    expire_in: 1 week

publish_bintray:
  stage: publish
  when: manual
  script:
    - "curl -X DELETE -umartykan:$BINTRAY_KEY https://api.bintray.com/content/airguard/firmware/esp32-main/1"
    - "curl -T .pio/build/esp32dev/firmware.bin -umartykan:$BINTRAY_KEY https://api.bintray.com/content/airguard/firmware/esp32-main/1/firmware.bin?publish=1"